import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { AppConfig } from '../../config/configuration.js';
import type { CommunityDto } from '@parallel/shared-types';
import { PrismaService } from '../../database/prisma.service.js';

@Injectable()
export class CommunitiesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly configService: ConfigService,
  ) {}

  async joinCommunity(userId: string, communityId: string): Promise<void> {
    const community = await this.prisma.community.findUnique({
      where: { id: communityId },
      select: { id: true },
    });

    if (!community) {
      throw new NotFoundException('Community not found');
    }

    const existingMembership = await this.prisma.communityMember.findUnique({
      where: {
        communityId_userId: {
          communityId,
          userId,
        },
      },
      select: {
        communityId: true,
      },
    });

    if (existingMembership) {
      throw new ConflictException('Already a member of this community');
    }

    await this.prisma.$transaction([
      this.prisma.communityMember.create({
        data: {
          communityId,
          userId,
        },
      }),
      this.prisma.interestSignal.create({
        data: {
          userId,
          signalType: 'COMMUNITY_JOIN',
          targetType: 'community',
          targetId: communityId,
          weight: 1.0,
        },
      }),
      // Joining supersedes any earlier skip. deleteMany (not delete) so this is a
      // no-op rather than an error when the user never skipped this community.
      this.prisma.communityDismissal.deleteMany({
        where: {
          userId,
          communityId,
        },
      }),
    ]);
  }

  async skipCommunity(userId: string, communityId: string): Promise<void> {
    const community = await this.prisma.community.findUnique({
      where: { id: communityId },
      select: { id: true },
    });

    if (!community) {
      throw new NotFoundException('Community not found');
    }

    const existingMembership = await this.prisma.communityMember.findUnique({
      where: {
        communityId_userId: {
          communityId,
          userId,
        },
      },
      select: {
        communityId: true,
      },
    });

    if (existingMembership) {
      throw new ConflictException('Already a member of this community');
    }

    // Skip is recommendation state only (no InterestSignal). Upsert keeps it
    // idempotent against the (userId, communityId) composite primary key.
    await this.prisma.communityDismissal.upsert({
      where: {
        userId_communityId: {
          userId,
          communityId,
        },
      },
      create: {
        userId,
        communityId,
      },
      update: {},
    });
  }

  async detectEmergentCommunities(): Promise<void> {
    const communityConfig =
      this.configService.get<AppConfig>('app')!.community;

    const qualifyingParallels = await this.prisma.userParallel.findMany({
      where: {
        strengthPct: {
          gte: communityConfig.minimumParallelStrength,
        },
        isGhost: false,
        isHidden: false,
        dismissedAt: null,
      },
      select: {
        userId: true,
        parallelTypeId: true,
      },
      orderBy: {
        userId: 'asc',
      },
    });

    const userParallels = new Map<string, Set<string>>();

    for (const parallel of qualifyingParallels) {
      const existing = userParallels.get(parallel.userId);

      if (existing) {
        existing.add(parallel.parallelTypeId);
      } else {
        userParallels.set(
          parallel.userId,
          new Set([parallel.parallelTypeId]),
        );
      }
    }

    const eligibleUsers = [...userParallels.entries()]
      .map(([userId, parallelTypeIds]) => ({
        userId,
        parallelTypeIds: [...parallelTypeIds].sort(),
      }))
      .filter(
        ({ parallelTypeIds }) =>
          parallelTypeIds.length >= communityConfig.minimumIntersectionSize,
      );

    const qualifyingIntersections = this.findQualifyingIntersections(
      eligibleUsers,
      communityConfig.minimumIntersectionSize,
      communityConfig.minimumMembers,
    );

    if (qualifyingIntersections.length === 0) {
      return;
    }

    const existingCommunities = await this.prisma.community.findMany({
      where: {
        autoGenerated: true,
      },
      select: {
        originatingParallelTypeIds: true,
      },
    });

    const existingKeys = new Set(
      existingCommunities.map((community) =>
        this.canonicalIntersectionKey(
          community.originatingParallelTypeIds as string[],
        ),
      ),
    );

    for (const intersection of qualifyingIntersections) {
      if (existingKeys.has(intersection.key)) {
        continue;
      }

      const parallelTypes = await this.prisma.parallelType.findMany({
        where: {
          id: {
            in: intersection.parallelTypeIds,
          },
        },
        select: {
          id: true,
          name: true,
        },
      });

      if (
        parallelTypes.length !== intersection.parallelTypeIds.length
      ) {
        continue;
      }

      const namesById = new Map(
        parallelTypes.map((parallelType) => [
          parallelType.id,
          parallelType.name,
        ]),
      );

      const nameParts = intersection.parallelTypeIds.map(
        (id) => namesById.get(id)!,
      );

      await this.prisma.community.create({
        data: {
          name: this.buildCommunityName(nameParts),
          description: `A community formed around ${nameParts.join(' + ')}.`,
          originatingParallelTypeIds: intersection.parallelTypeIds,
          autoGenerated: true,
        },
      });

      existingKeys.add(intersection.key);
    }
  }

  private findQualifyingIntersections(
    users: Array<{
      userId: string;
      parallelTypeIds: string[];
    }>,
    minimumSize: number,
    minimumMembers: number,
  ): Array<{
    key: string;
    parallelTypeIds: string[];
    memberCount: number;
  }> {
    const intersections = new Map<string, Set<string>>();

    for (const user of users) {
      this.addCombinations(
        user.parallelTypeIds,
        minimumSize,
        (combination) => {
          const key = combination.join('|');
          const members = intersections.get(key);

          if (members) {
            members.add(user.userId);
          } else {
            intersections.set(key, new Set([user.userId]));
          }
        },
      );
    }

    const qualifying = [...intersections.entries()]
      .filter(([, members]) => members.size >= minimumMembers)
      .map(([key, members]) => ({
        key,
        parallelTypeIds: key.split('|'),
        memberCount: members.size,
      }))
      .sort(
        (a, b) =>
          b.parallelTypeIds.length - a.parallelTypeIds.length ||
          b.memberCount - a.memberCount ||
          a.key.localeCompare(b.key),
      );

    return qualifying.filter(
      (candidate, index, all) =>
        !all.slice(0, index).some((larger) =>
          candidate.parallelTypeIds.every((id) =>
            larger.parallelTypeIds.includes(id),
          ),
        ),
    );
  }

  private addCombinations(
    values: string[],
    minimumSize: number,
    onCombination: (combination: string[]) => void,
  ): void {
    const visit = (
      start: number,
      combination: string[],
    ): void => {
      if (combination.length >= minimumSize) {
        onCombination(combination);
      }

      for (let index = start; index < values.length; index += 1) {
        combination.push(values[index]);
        visit(index + 1, combination);
        combination.pop();
      }
    };

    visit(0, []);
  }

  private canonicalIntersectionKey(ids: string[]): string {
    return [...ids].sort().join('|');
  }

  private buildCommunityName(parallelNames: string[]): string {
    const compactNames = parallelNames.map((name) =>
      name
        .split(/\s+/)
        .map((word) => word[0])
        .join('')
        .toUpperCase(),
    );

    return `${parallelNames.join(' + ')} (${compactNames.join('')})`;
  }

  async getCommunities(userId: string): Promise<CommunityDto[]> {
    const communityConfig =
      this.configService.get<AppConfig>('app')!.community;

    const visibleParallels = await this.prisma.userParallel.findMany({
      where: {
        userId,
        strengthPct: {
          gte: communityConfig.minimumParallelStrength,
        },
        isGhost: false,
        isHidden: false,
        dismissedAt: null,
      },
      select: {
        parallelTypeId: true,
      },
    });

    const visibleParallelIds = new Set(
      visibleParallels.map(({ parallelTypeId }) => parallelTypeId),
    );

    if (visibleParallelIds.size < communityConfig.minimumIntersectionSize) {
      return [];
    }

    const communities = await this.prisma.community.findMany({
      orderBy: {
        createdAt: 'desc',
      },
      include: {
        _count: {
          select: {
            members: true,
          },
        },
        members: {
          where: {
            userId,
          },
          select: {
            userId: true,
          },
        },
        dismissals: {
          where: {
            userId,
          },
          select: {
            userId: true,
          },
        },
      },
    });

    const matchingCommunities = communities.filter((community) => {
      const parallelIds =
        community.originatingParallelTypeIds as string[];

      return (
        parallelIds.length >= communityConfig.minimumIntersectionSize &&
        parallelIds.every((parallelId) => visibleParallelIds.has(parallelId)) &&
        community.dismissals.length === 0
      );
    });

    if (matchingCommunities.length === 0) {
      return [];
    }

    const parallelTypeIds = [
      ...new Set(
        matchingCommunities.flatMap(
          (community) =>
            community.originatingParallelTypeIds as string[],
        ),
      ),
    ];

    const parallelTypes = await this.prisma.parallelType.findMany({
      where: {
        id: {
          in: parallelTypeIds,
        },
      },
      select: {
        id: true,
        name: true,
      },
    });

    const parallelNames = new Map(
      parallelTypes.map((parallelType) => [
        parallelType.id,
        parallelType.name,
      ]),
    );

    return matchingCommunities.map((community) => {
      const originatingParallelTypeIds =
        community.originatingParallelTypeIds as string[];

      return {
        id: community.id,
        name: community.name,
        description: community.description,
        originatingParallelTypeIds,
        originatingParallelNames: originatingParallelTypeIds
          .map((id) => parallelNames.get(id))
          .filter((name): name is string => Boolean(name)),
        sharedParallelTypeIds: originatingParallelTypeIds.filter((id) =>
          visibleParallelIds.has(id),
        ),
        autoGenerated: community.autoGenerated,
        memberCount: community._count.members,
        isMember: community.members.length > 0,
        createdAt: community.createdAt.toISOString(),
      };
    });
  }
}
