import { Test, TestingModule } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';
import { ConflictException, NotFoundException } from '@nestjs/common';
import { CommunitiesService } from './communities.service.js';
import { PrismaService } from '../../database/prisma.service.js';

describe('CommunitiesService', () => {
  let service: CommunitiesService;

  let prisma: {
    community: Record<string, ReturnType<typeof vi.fn>>;
    communityMember: Record<string, ReturnType<typeof vi.fn>>;
    interestSignal: Record<string, ReturnType<typeof vi.fn>>;
    userParallel: Record<string, ReturnType<typeof vi.fn>>;
    parallelType: Record<string, ReturnType<typeof vi.fn>>;
    $transaction: ReturnType<typeof vi.fn>;
  };

  beforeEach(async () => {
    prisma = {
      community: {
        findUnique: vi.fn(),
        findMany: vi.fn(),
        create: vi.fn(),
      },
      communityMember: {
        findUnique: vi.fn(),
        create: vi.fn(),
      },
      interestSignal: {
        create: vi.fn(),
      },
      userParallel: {
        findMany: vi.fn(),
      },
      parallelType: {
        findMany: vi.fn(),
      },
      $transaction: vi.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CommunitiesService,
        {
          provide: ConfigService,
          useValue: {
            get: vi.fn().mockReturnValue({
              community: {
                minimumMembers: 5,
                minimumParallelStrength: 60,
                minimumIntersectionSize: 2,
              },
            }),
          },
        },
        { provide: PrismaService, useValue: prisma },
      ],
    }).compile();

    service = module.get(CommunitiesService);
  });

  it('creates a community when at least 5 users share 2 qualifying Parallels', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 5 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([]);

    prisma.parallelType.findMany.mockResolvedValue([
      {
        id: 'builder',
        name: 'Builder',
      },
      {
        id: 'music',
        name: 'Music',
      },
    ]);

    prisma.community.create = vi.fn().mockResolvedValue({
      id: 'community-1',
    });

    await service.detectEmergentCommunities();

    expect(prisma.community.create).toHaveBeenCalledOnce();

    expect(prisma.community.create).toHaveBeenCalledWith({
      data: {
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
      },
    });
  });

  it('does not create a community when fewer than 5 users qualify', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 4 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([]);

    await service.detectEmergentCommunities();

    expect(prisma.community.create).not.toHaveBeenCalled();
    expect(prisma.parallelType.findMany).not.toHaveBeenCalled();
  });

  it('does not create a community when the qualifying Parallel strength is below the configured threshold', async () => {
    prisma.userParallel.findMany.mockResolvedValue([]);

    prisma.community.findMany.mockResolvedValue([]);

    await service.detectEmergentCommunities();

    expect(prisma.community.create).not.toHaveBeenCalled();
  });

  it('does not create a duplicate community when the intersection already exists', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 5 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([
      {
        originatingParallelTypeIds: ['music', 'builder'],
      },
    ]);

    await service.detectEmergentCommunities();

    expect(prisma.community.create).not.toHaveBeenCalled();
    expect(prisma.parallelType.findMany).not.toHaveBeenCalled();
  });

  it('creates only the most-specific qualifying intersection', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 5 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'photography',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([]);

    prisma.parallelType.findMany.mockResolvedValue([
      {
        id: 'builder',
        name: 'Builder',
      },
      {
        id: 'music',
        name: 'Music',
      },
      {
        id: 'photography',
        name: 'Photography',
      },
    ]);

    prisma.community.create = vi.fn().mockResolvedValue({
      id: 'community-1',
    });

    await service.detectEmergentCommunities();

    expect(prisma.community.create).toHaveBeenCalledOnce();

    expect(prisma.community.create).toHaveBeenCalledWith({
      data: {
        name: 'Builder + Music + Photography (BMP)',
        description:
          'A community formed around Builder + Music + Photography.',
        originatingParallelTypeIds: [
          'builder',
          'music',
          'photography',
        ],
        autoGenerated: true,
      },
    });
  });

  it('returns communities with member counts', async () => {
    const createdAt = new Date('2026-09-20T10:00:00.000Z');

    prisma.community.findMany.mockResolvedValue([
      {
        id: 'community-1',
        name: 'Builders',
        description: 'People who build things.',
        originatingParallelTypeIds: ['parallel-1'],
        autoGenerated: false,
        createdAt,
        _count: {
          members: 3,
        },
      },
    ]);

    await expect(service.getCommunities()).resolves.toEqual([
      {
        id: 'community-1',
        name: 'Builders',
        description: 'People who build things.',
        originatingParallelTypeIds: ['parallel-1'],
        autoGenerated: false,
        memberCount: 3,
        createdAt: createdAt.toISOString(),
      },
    ]);
  });

  it('rejects joining a missing community', async () => {
    prisma.community.findUnique.mockResolvedValue(null);

    await expect(
      service.joinCommunity('user-1', 'missing'),
    ).rejects.toThrow(NotFoundException);

    expect(prisma.communityMember.findUnique).not.toHaveBeenCalled();
    expect(prisma.$transaction).not.toHaveBeenCalled();
  });

  it('rejects joining a community the user already belongs to', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue({
      communityId: 'community-1',
    });

    await expect(
      service.joinCommunity('user-1', 'community-1'),
    ).rejects.toThrow(ConflictException);

    expect(prisma.$transaction).not.toHaveBeenCalled();
  });

  it('joins a community and records the community join signal atomically', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    prisma.$transaction.mockResolvedValue([]);

    await expect(
      service.joinCommunity('user-1', 'community-1'),
    ).resolves.toBeUndefined();

    expect(prisma.$transaction).toHaveBeenCalledOnce();

    const operations = prisma.$transaction.mock.calls[0][0];

    expect(operations).toHaveLength(2);
  });
});
