import { Test, TestingModule } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';
import { ConflictException, NotFoundException } from '@nestjs/common';
import { CommunitiesService } from './communities.service.js';
import { PrismaService } from '../../database/prisma.service.js';

describe('CommunitiesService', () => {
  let service: CommunitiesService;

  let prisma: {
    community: Record<string, ReturnType<typeof vi.fn>>;
    communityMember: Record<string, ReturnType<typeof vi.fn>>;
    communityDismissal: Record<string, ReturnType<typeof vi.fn>>;
    interestSignal: Record<string, ReturnType<typeof vi.fn>>;
    userParallel: Record<string, ReturnType<typeof vi.fn>>;
    parallelType: Record<string, ReturnType<typeof vi.fn>>;
    $transaction: ReturnType<typeof vi.fn>;
  };

  beforeEach(async () => {
    prisma = {
      community: {
        findUnique: vi.fn(),
        findMany: vi.fn(),
        create: vi.fn(),
      },
      communityMember: {
        findUnique: vi.fn(),
        create: vi.fn(),
      },
      communityDismissal: {
        findUnique: vi.fn(),
        create: vi.fn(),
        upsert: vi.fn(),
        deleteMany: vi.fn(),
      },
      interestSignal: {
        create: vi.fn(),
      },
      userParallel: {
        findMany: vi.fn(),
      },
      parallelType: {
        findMany: vi.fn(),
      },
      $transaction: vi.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CommunitiesService,
        {
          provide: ConfigService,
          useValue: {
            get: vi.fn().mockReturnValue({
              community: {
                minimumMembers: 5,
                minimumParallelStrength: 60,
                minimumIntersectionSize: 2,
              },
            }),
          },
        },
        { provide: PrismaService, useValue: prisma },
      ],
    }).compile();

    service = module.get(CommunitiesService);
  });

  it('creates a community when at least 5 users share 2 qualifying Parallels', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 5 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([]);

    prisma.parallelType.findMany.mockResolvedValue([
      {
        id: 'builder',
        name: 'Builder',
      },
      {
        id: 'music',
        name: 'Music',
      },
    ]);

    prisma.community.create = vi.fn().mockResolvedValue({
      id: 'community-1',
    });

    await service.detectEmergentCommunities();

    expect(prisma.community.create).toHaveBeenCalledOnce();

    expect(prisma.community.create).toHaveBeenCalledWith({
      data: {
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
      },
    });
  });

  it('does not create a community when fewer than 5 users qualify', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 4 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([]);

    await service.detectEmergentCommunities();

    expect(prisma.community.create).not.toHaveBeenCalled();
    expect(prisma.parallelType.findMany).not.toHaveBeenCalled();
  });

  it('does not create a community when the qualifying Parallel strength is below the configured threshold', async () => {
    prisma.userParallel.findMany.mockResolvedValue([]);

    prisma.community.findMany.mockResolvedValue([]);

    await service.detectEmergentCommunities();

    expect(prisma.community.create).not.toHaveBeenCalled();
  });

  it('does not create a duplicate community when the intersection already exists', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 5 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([
      {
        originatingParallelTypeIds: ['music', 'builder'],
      },
    ]);

    await service.detectEmergentCommunities();

    expect(prisma.community.create).not.toHaveBeenCalled();
    expect(prisma.parallelType.findMany).not.toHaveBeenCalled();
  });

  it('creates only the most-specific qualifying intersection', async () => {
    prisma.userParallel.findMany.mockResolvedValue(
      Array.from({ length: 5 }, (_, index) => [
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'builder',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'music',
        },
        {
          userId: `user-${index + 1}`,
          parallelTypeId: 'photography',
        },
      ]).flat(),
    );

    prisma.community.findMany.mockResolvedValue([]);

    prisma.parallelType.findMany.mockResolvedValue([
      {
        id: 'builder',
        name: 'Builder',
      },
      {
        id: 'music',
        name: 'Music',
      },
      {
        id: 'photography',
        name: 'Photography',
      },
    ]);

    prisma.community.create = vi.fn().mockResolvedValue({
      id: 'community-1',
    });

    await service.detectEmergentCommunities();

    expect(prisma.community.create).toHaveBeenCalledOnce();

    expect(prisma.community.create).toHaveBeenCalledWith({
      data: {
        name: 'Builder + Music + Photography (BMP)',
        description:
          'A community formed around Builder + Music + Photography.',
        originatingParallelTypeIds: [
          'builder',
          'music',
          'photography',
        ],
        autoGenerated: true,
      },
    });
  });

  it('returns communities matching the user visible Parallels', async () => {
    const createdAt = new Date('2026-09-20T10:00:00.000Z');

    prisma.userParallel.findMany.mockResolvedValue([
      {
        parallelTypeId: 'builder',
      },
      {
        parallelTypeId: 'music',
      },
    ]);

    prisma.community.findMany.mockResolvedValue([
      {
        id: 'community-1',
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
        createdAt,
        _count: {
          members: 3,
        },
        members: [],
        dismissals: [],
      },
    ]);

    prisma.parallelType.findMany.mockResolvedValue([
      {
        id: 'builder',
        name: 'Builder',
      },
      {
        id: 'music',
        name: 'Music',
      },
    ]);

    await expect(service.getCommunities('user-1')).resolves.toEqual([
      {
        id: 'community-1',
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        originatingParallelNames: ['Builder', 'Music'],
        sharedParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
        memberCount: 3,
        isMember: false,
        createdAt: createdAt.toISOString(),
      },
    ]);
  });

  it('does not recommend a community when the user is missing a required Parallel', async () => {
    prisma.userParallel.findMany.mockResolvedValue([
      {
        parallelTypeId: 'builder',
      },
    ]);

    prisma.community.findMany.mockResolvedValue([
      {
        id: 'community-1',
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
        createdAt: new Date('2026-09-20T10:00:00.000Z'),
        _count: {
          members: 5,
        },
        members: [],
        dismissals: [],
      },
    ]);

    await expect(service.getCommunities('user-1')).resolves.toEqual([]);

    expect(prisma.parallelType.findMany).not.toHaveBeenCalled();
  });

  it('does not recommend a community the user has dismissed', async () => {
    prisma.userParallel.findMany.mockResolvedValue([
      {
        parallelTypeId: 'builder',
      },
      {
        parallelTypeId: 'music',
      },
    ]);

    prisma.community.findMany.mockResolvedValue([
      {
        id: 'community-1',
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
        createdAt: new Date('2026-09-20T10:00:00.000Z'),
        _count: {
          members: 5,
        },
        members: [],
        dismissals: [
          {
            userId: 'user-1',
          },
        ],
      },
    ]);

    await expect(service.getCommunities('user-1')).resolves.toEqual([]);

    expect(prisma.parallelType.findMany).not.toHaveBeenCalled();
  });

  it('marks a community as a member recommendation when the user is already a member', async () => {
    prisma.userParallel.findMany.mockResolvedValue([
      {
        parallelTypeId: 'builder',
      },
      {
        parallelTypeId: 'music',
      },
    ]);

    prisma.community.findMany.mockResolvedValue([
      {
        id: 'community-1',
        name: 'Builder + Music (BM)',
        description: 'A community formed around Builder + Music.',
        originatingParallelTypeIds: ['builder', 'music'],
        autoGenerated: true,
        createdAt: new Date('2026-09-20T10:00:00.000Z'),
        _count: {
          members: 6,
        },
        members: [
          {
            userId: 'user-1',
          },
        ],
        dismissals: [],
      },
    ]);

    prisma.parallelType.findMany.mockResolvedValue([
      {
        id: 'builder',
        name: 'Builder',
      },
      {
        id: 'music',
        name: 'Music',
      },
    ]);

    const result = await service.getCommunities('user-1');

    expect(result[0].isMember).toBe(true);
  });

  it('rejects joining a missing community', async () => {
    prisma.community.findUnique.mockResolvedValue(null);

    await expect(
      service.joinCommunity('user-1', 'missing'),
    ).rejects.toThrow(NotFoundException);

    expect(prisma.communityMember.findUnique).not.toHaveBeenCalled();
    expect(prisma.$transaction).not.toHaveBeenCalled();
  });

  it('rejects joining a community the user already belongs to', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue({
      communityId: 'community-1',
    });

    await expect(
      service.joinCommunity('user-1', 'community-1'),
    ).rejects.toThrow(ConflictException);

    expect(prisma.$transaction).not.toHaveBeenCalled();
  });

  it('joins a community and records the community join signal atomically', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    prisma.$transaction.mockResolvedValue([]);

    await expect(
      service.joinCommunity('user-1', 'community-1'),
    ).resolves.toBeUndefined();

    expect(prisma.$transaction).toHaveBeenCalledOnce();

    const operations = prisma.$transaction.mock.calls[0][0];

    expect(operations).toHaveLength(3);

    expect(prisma.communityMember.create).toHaveBeenCalledWith({
      data: {
        communityId: 'community-1',
        userId: 'user-1',
      },
    });

    expect(prisma.interestSignal.create).toHaveBeenCalledWith({
      data: {
        userId: 'user-1',
        signalType: 'COMMUNITY_JOIN',
        targetType: 'community',
        targetId: 'community-1',
        weight: 1.0,
      },
    });
  });

  it('removes a previous dismissal in the same transaction when joining a skipped community', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    prisma.$transaction.mockResolvedValue([]);

    await service.joinCommunity('user-1', 'community-1');

    expect(prisma.communityDismissal.deleteMany).toHaveBeenCalledWith({
      where: {
        userId: 'user-1',
        communityId: 'community-1',
      },
    });

    expect(prisma.$transaction).toHaveBeenCalledOnce();
    expect(prisma.$transaction.mock.calls[0][0]).toHaveLength(3);
  });

  it('joins normally when the user never skipped the community', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    // deleteMany matching zero rows is not an error.
    prisma.communityDismissal.deleteMany.mockResolvedValue({ count: 0 });
    prisma.$transaction.mockResolvedValue([]);

    await expect(
      service.joinCommunity('user-1', 'community-1'),
    ).resolves.toBeUndefined();

    expect(prisma.communityMember.create).toHaveBeenCalledOnce();
    expect(prisma.interestSignal.create).toHaveBeenCalledOnce();
  });

  it('rejects skipping a missing community', async () => {
    prisma.community.findUnique.mockResolvedValue(null);

    await expect(
      service.skipCommunity('user-1', 'missing'),
    ).rejects.toThrow(NotFoundException);

    expect(prisma.communityMember.findUnique).not.toHaveBeenCalled();
    expect(prisma.communityDismissal.upsert).not.toHaveBeenCalled();
  });

  it('rejects skipping a community the user already belongs to', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue({
      communityId: 'community-1',
    });

    await expect(
      service.skipCommunity('user-1', 'community-1'),
    ).rejects.toThrow(ConflictException);

    expect(prisma.communityDismissal.upsert).not.toHaveBeenCalled();
  });

  it('persists a dismissal when skipping a community', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    prisma.communityDismissal.upsert.mockResolvedValue({
      userId: 'user-1',
      communityId: 'community-1',
    });

    await expect(
      service.skipCommunity('user-1', 'community-1'),
    ).resolves.toBeUndefined();

    expect(prisma.communityDismissal.upsert).toHaveBeenCalledWith({
      where: {
        userId_communityId: {
          userId: 'user-1',
          communityId: 'community-1',
        },
      },
      create: {
        userId: 'user-1',
        communityId: 'community-1',
      },
      update: {},
    });
  });

  it('skips idempotently without creating duplicate dismissals', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    prisma.communityDismissal.upsert.mockResolvedValue({
      userId: 'user-1',
      communityId: 'community-1',
    });

    await service.skipCommunity('user-1', 'community-1');

    await expect(
      service.skipCommunity('user-1', 'community-1'),
    ).resolves.toBeUndefined();

    expect(prisma.communityDismissal.upsert).toHaveBeenCalledTimes(2);
    // Plain create would violate the composite primary key on the second call.
    expect(prisma.communityDismissal.create).not.toHaveBeenCalled();
  });

  it('does not record an interest signal or membership when skipping', async () => {
    prisma.community.findUnique.mockResolvedValue({
      id: 'community-1',
    });

    prisma.communityMember.findUnique.mockResolvedValue(null);

    prisma.communityDismissal.upsert.mockResolvedValue({
      userId: 'user-1',
      communityId: 'community-1',
    });

    await service.skipCommunity('user-1', 'community-1');

    expect(prisma.interestSignal.create).not.toHaveBeenCalled();
    expect(prisma.communityMember.create).not.toHaveBeenCalled();
    expect(prisma.$transaction).not.toHaveBeenCalled();
  });
});
